#!/usr/bin/env python
"""fips main entry"""
import os
import sys
import subprocess
proj_path = os.path.dirname(os.path.abspath(__file__))
fips_path = os.path.join(os.path.dirname(proj_path), 'Src', 'Third', 'fips')
if not os.path.isdir(fips_path) :
    print("\033[91m[ERROR]\033[0m incorrect path to fips in '{}'".format(fips_path)) 
    sys.exit(10) 
sys.path.insert(0,fips_path)
try :
    from mod import fips
except ImportError :
    print("\033[91m[ERROR]\033[0m failed to initialize fips build system in '{}'".format(proj_path)) 
    sys.exit(10)
fips.run(fips_path, proj_path, sys.argv)
